[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "chmod +x ./node_modules/.bin/nest",
  "npx nest build"
]

[phases.start]
cmds = ["npm start"]