services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vishwa1720@1720
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
  app:
    build: .
    container_name: nest_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: Vishwa1720@1720
      DB_NAME: product_catalog
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TTL: 300
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
  redis-data: 