[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "npm ci",
  "chmod +x node_modules/.bin/*"
]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run start:prod"